# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b8d72ef8260bdef8c7e5f792dad3527e146b514d041c8e192ac0da3ebeb8240932054d1f51e60d1f2c68cdd0e63942723b03d41ac0cb5df777d3870aa96524bb

test:
  secret_key_base: 49e213eb4b79da704b7eb17e380984e6e8a3c89ee2c2b963e870c8ed58c1b4e59780af6582c1a17f8cb37722214125f98331b48bf418e7ea04d473030a8b45b4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
